/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_a10_infohub_fix_DexManager */

#ifndef _Included_com_a10_infohub_fix_DexManager
#define _Included_com_a10_infohub_fix_DexManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_a10_infohub_fix_DexManager
 * Method:    replace
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_com_a10_infohub_fix_DexManager_replace
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
